matrix:
  include:
  - language: c
    sudo: false
    cache:
      directories:
        - ~/arduino_ide
        - ~/.arduino15/packages/
    git:
      depth: false
      quiet: true
    env:
      global:
        - ARDUINO_IDE_VERSION="1.8.7"
    before_install:
      - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
    install:
      - arduino --install-library "Adafruit SleepyDog Library","Adafruit FONA Library"
    script:
      - build_main_platforms
  - language: python
    python:
    - 3.5
    cache: pip
    install:
    - pip install -q cpplint
    script:
    - python -m cpplint --extensions=ino --linelength=80 --filter=-runtime/int Arduino/LCD_racing_car/racing_car.ino
